import { InnovationPlaybook } from "./types";

export const INNOVATION_PLAYBOOKS: InnovationPlaybook[] = [
  {
    id: "cinema-director",
    badge: "HERO",
    title: "Auteur Cinema Director",
    tagline: "Brief-to-episodic 5-act cinema narrative",
    description: "Autonomous multi-agent director that synthesizes 3 creative territories, plans camera geometry, and audits continuity against director specs.",
    category: "cinema",
    defaultBrief: "A cyber-noir operative infiltrates an orbital cryogenic server vault suspended above a tempest ocean. Panavision C-Series anamorphic glass, cold cyan halogen rim lighting, slow-creeping shadows, and pressurized steam bursting through titanium bulkheads.",
    costEstimate: "$0.04/shot · $0.12 run",
    toolsUsed: ["Livepeer CogVideoX", "Visual Critic Agent", "Aesthetic Memory Loop"],
    recommendedAspectRatio: "2.39:1",
  },
  {
    id: "muse-reference",
    badge: "HERO",
    title: "Muse — Reference-to-Creation",
    tagline: "Extract reference craft, build original cut",
    description: "Ingest a reference visual or video aesthetic, extract cinematic lighting, framing, and pacing, and synthesize an original narrative sequence.",
    category: "muse",
    defaultBrief: "High-velocity orbital interception: a mirror-finish research vessel aligns with an ancient Dyson swarm structure under blazing solar corona backlighting. Tactile cockpit switches, HUD vector calculations, zero-gravity floating debris, and ultra-crisp deep space contrast.",
    costEstimate: "$0.02 ref · $0.04/shot",
    toolsUsed: ["Livepeer Vision CV", "Prompt Synthesizer", "Livepeer CogVideoX"],
    recommendedAspectRatio: "2.39:1",
  },
  {
    id: "breaking-news",
    badge: "HERO",
    title: "Breaking-News Flash",
    tagline: "Cinematic b-roll with real broadcast HUD",
    description: "High-urgency broadcast journalism pipeline that pairs documentary b-roll with animated lower-thirds, telemetry feeds, and breaking news tickers.",
    category: "broadcast",
    defaultBrief: "Deep-abyss bathyscaphe expedition uncovers a colossal crystalline obelisk at the floor of the Mariana Trench emitting bioluminescent thermal pulses. Sonar telemetry sweeps, murky particulate scatter, high-intensity tungsten floodlights, and eerie hydrophone reverberation.",
    costEstimate: "$0.08 - $0.20/reel",
    toolsUsed: ["Broadcast HUD", "Subnet Render", "HyperFrames Audio"],
    recommendedAspectRatio: "16:9",
  },
  {
    id: "fashion-lookbook",
    badge: "HERO",
    title: "E-Commerce Lookbook",
    tagline: "Cinematic fashion cuts with product framing",
    description: "Commercial-grade fashion cuts featuring high-speed slow-motion fabric dynamics, studio rim lighting, and focal rack-focus transitions.",
    category: "lookbook",
    defaultBrief: "Avant-garde architectural streetwear film: sculptural obsidian technical garments cutting through windward Icelandic black sand dunes and geothermal steam vents. High-speed 120fps fabric billowing, raw volcanic textures, macro zipper pulls, and stark overcast diffuse lighting.",
    costEstimate: "$0.05 - $0.15/reel",
    toolsUsed: ["Livepeer CogVideoX", "Rim Lighting Filter", "Aspect Crop Engine"],
    recommendedAspectRatio: "9:16",
  },
  {
    id: "typographic-social",
    badge: "HERO",
    title: "Typographic Social Cut",
    tagline: "Word-hit captions & kinetic on-video type",
    description: "Fast-cut vertical social cut with synchronized timecode, punchy camera dollies, and procedural audio accents.",
    category: "social",
    defaultBrief: "Fast-paced kinetic countdown of the 3 breakthrough decentralized AI models transforming autonomous filmmaking in 2026.",
    costEstimate: "$0.04 - $0.10/cut",
    toolsUsed: ["Kinetic Type Sync", "Livepeer Agent Video", "Web Audio Accents"],
    recommendedAspectRatio: "9:16",
  },
  {
    id: "storyboard-grid",
    badge: "HERO",
    title: "Product Storyboard 9-Grid",
    tagline: "One SKU, 9 editorial frames with identity lock",
    description: "Curate a 3x3 brand-portfolio board (hero, macro, lifestyle, isometric) with persistent identity locked across every cell.",
    category: "product",
    defaultBrief: "Matte-black obsidian chronograph with exposed tourbillon escapement: macro bezel texture, floating exploded dial components, and studio lighting.",
    costEstimate: "$0.06 - $0.18/board",
    toolsUsed: ["Identity Lock DAG", "Livepeer AI T2I", "HyperFrames Grid"],
    recommendedAspectRatio: "1:1",
  },
];
